Models/Contest.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Mathemat.io.Models
{
    public class Contest
    {
        public enum DifficultyLevel
        {
            Low,
            Medium,
            High
        }

        public enum StatusLevel
        {
            NotStarted,
            InProgress,
            Finished,
            ResultsOut
        }

        [Key]
        public int ContestID { get; set; }

        [Required]
        [StringLength(100)]
        public string Title { get; set; } = String.Empty;

        public DifficultyLevel Difficulty { get; set; }

        [Required]
        [DataType(DataType.DateTime)]
        public DateTime StartDate { get; set; }

        [Required]
        public StatusLevel Status { get; set; }

        public int Duration { get; set; }

        [NotMapped]
        public IEnumerable<int>? JudgeIDs { get; set; }

        [NotMapped]
        public IEnumerable<int>? ProblemIDs { get; set; }

        [NotMapped]
        public IEnumerable<int>? ParticipantIDs { get; set; }

        public ICollection<Mentor> Judges { get; set; }

        public ICollection<Contestant> Participants { get; set; }

        public ICollection<Problem> Problems { get; set; }



    }
}

Controllers/ContestsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Mathemat.io.Data;
using Mathemat.io.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Mathematio.Areas.Identity.Data;

namespace Mathematio.Controllers
{
    public class ContestsController : Controller
    {
        private readonly MathematioContext _context;
        public IServiceProvider _serviceProvider;

        public ContestsController(MathematioContext context,IServiceProvider serviceProvider)
        {
            _context = context;
            _serviceProvider = serviceProvider;
        }

        // GET: Contests
        public async Task<IActionResult> Index(string? title,int? difficulty,int? status)
        {
            var contests = _context.Contests.ToList();
            contests = contests.Select(c =>
            {
                DateTime sd = c.StartDate;
                if (DateTime.Now.CompareTo(sd) > 0 && DateTime.Now.CompareTo(sd.AddMinutes(c.Duration)) < 0)
                {
                    c.Status = Contest.StatusLevel.InProgress;
                }
                if (DateTime.Now.CompareTo(sd.AddMinutes(c.Duration)) > 0 && c.Status!=Contest.StatusLevel.ResultsOut)
                {
                    c.Status = Contest.StatusLevel.Finished;
                }
                _context.Contests.Update(c);
                _context.SaveChanges();
                return c;
            }).ToList();
            var contestFilter = _context.Contests.AsQueryable();
            if (!string.IsNullOrEmpty(title))
            {
                contestFilter = contestFilter.Where(c => c.Title.Contains(title));
            }
            if(difficulty != null)
            {
                contestFilter = contestFilter.Where(c => (int)c.Difficulty == difficulty);
            }
            if(status != null)
            {
                contestFilter = contestFilter.Where(c => (int)c.Status == status);
            }
            return View(await contestFilter.ToListAsync());
        }

        // GET: Contests/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Contests == null)
            {
                return NotFound();
            }

            var contest = await _context.Contests
                .FirstOrDefaultAsync(m => m.ContestID == id);
            if (contest == null)
            {
                return NotFound();
            }

            return View(contest);
        }

        // GET: Contests/Create
        [Authorize(Roles = "Admin,Mentor")]
        public IActionResult Create()
        {
            //var userService = _serviceProvider.GetRequiredService<UserManager<MathematioUser>>();
            //var user = userService.GetUserAsync(HttpContext.User);
            ViewBag.Judges = new SelectList(_context.Set<Mentor>(), "MentorID", "FirstName");
            ViewBag.Problems = new SelectList(_context.Set<Problem>(), "ProblemId", "Title");
            ViewBag.Participants = new SelectList(_context.Set<Contestant>(), "ContestantID", "FirstName");
            return View();
        }

        // POST: Contests/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Mentor")]
        public async Task<IActionResult> Create([Bind("ContestID,Title,Difficulty,StartDate,Status,Duration,JudgeIDs,ProblemIDs,ParticipantIDs")] Contest contest)
        {
            if (ModelState.IsValid)
            {
                _context.Add(contest);
                await _context.SaveChangesAsync();
                foreach (var JudgeID in contest.JudgeIDs)
                {
                    ContestJudges contestJudges = new ContestJudges();
                    contestJudges.MentorID = JudgeID;
                    contestJudges.ContestID = contest.ContestID;
                    await _context.AddAsync<ContestJudges>(contestJudges);
                }
                foreach (var ProblemID in contest.ProblemIDs)
                {
                    ContestProblems contestProblems = new ContestProblems();
                    contestProblems.ContestID = contest.ContestID;
                    contestProblems.ProblemID = ProblemID;
                    await _context.AddAsync<ContestProblems>(contestProblems);
                }
                foreach (var ParticipantID in contest.ParticipantIDs)
                {
                    Participants participant = new Participants();
                    participant.ContestID = contest.ContestID;
                    participant.ContestantID = ParticipantID;
                    await _context.AddAsync<Participants>(participant);
                }
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(contest);
        }

        // GET: Contests/Edit/5
        [Authorize(Roles = "Admin,Mentor")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Contests == null)
            {
                return NotFound();
            }

            var contest = await _context.Contests.FindAsync(id);
            if (contest == null)
            {
                return NotFound();
            }
            return View(contest);
        }

        // POST: Contests/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Mentor")]
        public async Task<IActionResult> Edit(int id, [Bind("ContestID,Title,Difficulty,StartDate,Status,Duration")] Contest contest)
        {
            if (id != contest.ContestID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(contest);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ContestExists(contest.ContestID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(contest);
        }

        // GET: Contests/Delete/5
        [Authorize(Roles = "Admin,Mentor")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Contests == null)
            {
                return NotFound();
            }

            var contest = await _context.Contests
                .FirstOrDefaultAsync(m => m.ContestID == id);
            if (contest == null)
            {
                return NotFound();
            }

            return View(contest);
        }

        // POST: Contests/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Mentor")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Contests == null)
            {
                return Problem("Entity set 'MathematioContext.Contests'  is null.");
            }
            var contest = await _context.Contests.FindAsync(id);
            if (contest != null)
            {
                _context.Contests.Remove(contest);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ContestExists(int id)
        {
            return (_context.Contests?.Any(e => e.ContestID == id)).GetValueOrDefault();
        }


        public async Task<IActionResult> Start(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var userManager = _serviceProvider.GetRequiredService<UserManager<MathematioUser>>();
            var userID = userManager.FindByNameAsync(User.Identity.Name).Result.LinkId;
            if(!_context.Participants.Any(p=>p.ContestID==id && p.ContestantID == userID))
            {
                return NotFound();
            }
            var contest = _context.Contests.Find(id);
            if(contest.Status != Contest.StatusLevel.InProgress)
            {
                return NotFound();
            }
            ViewBag.Contest = _context.Contests.Find(id);
            var problems = await _context.ContestProblems.Where(cp => cp.ContestID == id).Select(cp => cp.Problem).ToListAsync<Problem>();
            return View(problems);

        }

        [Route("Contests/Submit/{id:int}/{problemId:int}")]
        public async Task<IActionResult> Submit(int? id, int? problemId)
        {
            if (id == null || problemId == null)
            {
                return NotFound();
            }

            ContestSubmissions submission = new ContestSubmissions();
            submission.ProblemID = (int)problemId;
            submission.ContestID = (int)id;

            return View(submission);
        }

        [HttpPost]
        [Route("Contests/SubmitConfirmed/{id:int}/{problemId:int}")]
        public async Task<IActionResult> SubmitConfirmed(int? id, int? problemId, [Bind("ContestID", "ProblemID", "ContestantID", "Solution", "SolutionFile")] ContestSubmissions submission)
        {
            if (submission.SolutionFile != null)
            {

Views/Contests/Create.cshtml
@model Mathemat.io.Models.Contest

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Contest</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Difficulty" class="control-label"></label>
                <select asp-for="Difficulty" class="form-control">
                    <option value="0">Easy</option>
                    <option value="1">Medium</option>
                    <option value="2">Hard</option>
                </select>
                <span asp-validation-for="Difficulty" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <select asp-for="Status" class="form-control">
                    <option value="0">NotStarted</option>
                    <option value="1">InProgress</option>
                    <option value="2">Finished</option>
                </select>
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Duration" class="control-label"></label>
                <input asp-for="Duration" class="form-control" />
                <span asp-validation-for="Duration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="JudgeIDs" class="control-label"></label>
                <select asp-for="JudgeIDs" multiple class="form-control select-chosen" asp-items="ViewBag.Judges">
                </select>
                <span asp-validation-for="JudgeIDs" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProblemIDs" class="control-label"></label>
                <select asp-for="ProblemIDs" class="form-control" asp-items="ViewBag.Problems">
                </select>
                <span asp-validation-for="ProblemIDs" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ParticipantIDs" class="control-label"></label>
                <select asp-for="ParticipantIDs" class="form-control" asp-items="ViewBag.Participants">
                </select>
                <span asp-validation-for="ParticipantIDs" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Contests/Delete.cshtml
@model Mathemat.io.Models.Contest

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Contest</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Difficulty)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Difficulty)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Duration)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Duration)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ContestID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Contests/Details.cshtml
@model Mathemat.io.Models.Contest

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Contest</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Difficulty)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Difficulty)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Duration)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Duration)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.ContestID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Contests/Edit.cshtml
@model Mathemat.io.Models.Contest

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Contest</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ContestID" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Difficulty" class="control-label"></label>
                <select asp-for="Difficulty" class="form-control"></select>
                <span asp-validation-for="Difficulty" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <select asp-for="Status" class="form-control"></select>
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Duration" class="control-label"></label>
                <input asp-for="Duration" class="form-control" />
                <span asp-validation-for="Duration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Contests/Index.cshtml
@model IEnumerable<Mathemat.io.Models.Contest>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>
<form asp-controller="Contests" asp-action="Index" method="get">
    <label>Title</label>
    <input type="text" name="title"/>

    <label>Difficulty</label>
    <select name="difficulty">
        <option value="">All</option>
        <option value="0">Easy</option>
        <option value="1">Medium</option>
        <option value="2">Hard</option>
    </select>

    <label>Status</label>
    <select name="status">
        <option value="">All</option>
        <option value="0">Not Started</option>
        <option value="1">In Progress</option>
        <option value="2">Finished</option>
    </select>

    <button class="btn btn-info" type="submit">Filter</button>
</form>
<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Difficulty)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Duration)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Difficulty)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Duration)
            </td>
            <td>
                <a class="btn btn-light" asp-action="Edit" asp-route-id="@item.ContestID">Edit</a> 
                <a class="btn btn-light" asp-action="Details" asp-route-id="@item.ContestID">Details</a> 
                <a class="btn btn-light" asp-action="Delete" asp-route-id="@item.ContestID">Delete</a> 
                <a class="btn btn-light" asp-action="Start" asp-route-id="@item.ContestID">Start</a> 
                <a class="btn btn-light" asp-action="Submissions" asp-route-id="@item.ContestID">Submissions</a> 
                <a class="btn btn-light" asp-action="Results" asp-route-id="@item.ContestID">Results</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Contests/Results.cshtml
@model IEnumerable<Mathemat.io.Models.ContestSubmissions>

@{
    ViewData["Title"] = "Results";
}

<h1>Results</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Points)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Contestant)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Points)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Contestant.FirstName)
            </td>
        </tr>
}
    </tbody>
</table>

Views/Contests/Start.cshtml
@model IEnumerable<Mathemat.io.Models.Problem>
@{
    ViewData["Title"] = "Start";
}
@{
    var id = this.ViewContext.RouteData.Values["id"];
}

<h1>Start</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Difficulty)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Difficulty)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                <a asp-controller="Contests" asp-action="Submit" asp-route-id="@id" asp-route-problemId="@item.ProblemId" >Submit</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Contests/Submissions.cshtml
@model IEnumerable<Mathemat.io.Models.ContestSubmissions>

@{
    ViewData["Title"] = "Submissions";
}

<h1>Submissions</h1>

<form asp-controller="Contests" asp-action="ResultsOut" method="post">
    <input name="id" value="@Model.First().ContestID" type="hidden" />
    <button class="btn btn-success" type="submit">Publish results</button>
</form>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Solution)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Points)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Contest)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Problem.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Contestant.FirstName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                <a href="~/profilePictures/@Html.DisplayFor(modelItem => item.Solution)">@Html.DisplayFor(modelItem => item.Solution)</a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Points)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Contest.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Problem.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Contestant.FirstName)
            </td>
            <td>
                <a asp-action="SubmissionsEdit" asp-route-contestID="@item.ContestID" asp-route-problemID="@item.ProblemID" asp-route-contestantID="@item.ContestantID">Grade</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Contests/SubmissionsEdit.cshtml
@model Mathemat.io.Models.ContestSubmissions

@{
    ViewData["Title"] = "SubmissionsEdit";
}

<h1>SubmissionsEdit</h1>

<h4>ContestSubmissions</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="SubmissionsEdit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ContestID" />
            <input type="hidden" asp-for="ProblemID" />
            <input type="hidden" asp-for="ContestantID" />
            <div class="form-group">
                <label asp-for="Solution" class="control-label"></label>
                <input asp-for="Solution" class="form-control" />
                <span asp-validation-for="Solution" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Points" class="control-label"></label>
                <input asp-for="Points" class="form-control" />
                <span asp-validation-for="Points" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Contests/Submit.cshtml
@model Mathemat.io.Models.ContestSubmissions
@{
    ViewData["Title"] = "Submit";
}

<h1>Submit</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="Contests" asp-action="SubmitConfirmed" asp-route-id="@Model.ContestID" asp-route-problemId="@Model.ProblemID" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ContestID" />
            <input type="hidden" asp-for="ProblemID" />
            <input type="hidden" asp-for="ContestantID" />
            <div class="form-group">
                <label asp-for="SolutionFile" class="control-label"></label>
                <div class="custom-file">
                    <input asp-for="SolutionFile" class="custom-file-input" id="customFile">
                    <label class="custom-file-label" for="customFile"></label>
                </div>
                <span asp-validation-for="SolutionFile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Start" asp-route-id="@Model.ContestID">Back</a>
</div>