Models/Area.cs
using System.Collections;
using System.ComponentModel.DataAnnotations;

namespace Mathemat.io.Models
{
    public class Area
    {
        [Key]
        public int AreaID { get; set; }

        [Required]
        [StringLength(30)]
        public string Name { get; set; } = String.Empty;

        [Required]
        [StringLength(100)]
        public string Description { get;set; } = String.Empty;

        public ICollection<Problem> Problems { get; set; }

    }
}

Areas/Identity/Pages/Account/AccessDenied.cshtml.cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
#nullable disable

using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Mathematio.Areas.Identity.Pages.Account
{
    /// <summary>
    ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
    ///     directly from your code. This API may change or be removed in future releases.
    /// </summary>
    public class AccessDeniedModel : PageModel
    {
        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        public void OnGet()
        {
        }
    }
}

Areas/Identity/Pages/Account/Logout.cshtml.cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
#nullable disable

using System;
using System.Threading.Tasks;
using Mathematio.Areas.Identity.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Mathematio.Areas.Identity.Pages.Account
{
    public class LogoutModel : PageModel
    {
        private readonly SignInManager<MathematioUser> _signInManager;
        private readonly ILogger<LogoutModel> _logger;

        public LogoutModel(SignInManager<MathematioUser> signInManager, ILogger<LogoutModel> logger)
        {
            _signInManager = signInManager;
            _logger = logger;
        }

        public async Task<IActionResult> OnPost(string returnUrl = null)
        {
            await _signInManager.SignOutAsync();
            _logger.LogInformation("User logged out.");
            if (returnUrl != null)
            {
                return LocalRedirect(returnUrl);
            }
            else
            {
                // This needs to be a redirect so that the browser performs a new
                // request and the identity for the user gets updated.
                return RedirectToPage();
            }
        }
    }
}

Controllers/AreasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Mathemat.io.Data;
using Mathemat.io.Models;
using Microsoft.AspNetCore.Authorization;

namespace Mathematio.Controllers
{
    public class AreasController : Controller
    {
        private readonly MathematioContext _context;

        public AreasController(MathematioContext context)
        {
            _context = context;
        }

        // GET: Areas
        public async Task<IActionResult> Index(string? name)
        {
            var areaFilter = _context.Areas.AsQueryable();
            if (!string.IsNullOrEmpty(name))
            {
                areaFilter = areaFilter.Where(x => x.Name.Contains(name));
            }
            return View(await areaFilter.ToListAsync());
        }

        // GET: Areas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Areas == null)
            {
                return NotFound();
            }

            var area = await _context.Areas
                .FirstOrDefaultAsync(m => m.AreaID == id);
            if (area == null)
            {
                return NotFound();
            }

            return View(area);
        }

        // GET: Areas/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Areas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("AreaID,Name,Description")] Area area)
        {
            if (ModelState.IsValid)
            {
                _context.Add(area);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(area);
        }

        // GET: Areas/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Areas == null)
            {
                return NotFound();
            }

            var area = await _context.Areas.FindAsync(id);
            if (area == null)
            {
                return NotFound();
            }
            return View(area);
        }

        // POST: Areas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("AreaID,Name,Description")] Area area)
        {
            if (id != area.AreaID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(area);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AreaExists(area.AreaID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(area);
        }

        // GET: Areas/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Areas == null)
            {
                return NotFound();
            }

            var area = await _context.Areas
                .FirstOrDefaultAsync(m => m.AreaID == id);
            if (area == null)
            {
                return NotFound();
            }

            return View(area);
        }

        // POST: Areas/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Areas == null)
            {
                return Problem("Entity set 'MathematioContext.Areas'  is null.");
            }
            var area = await _context.Areas.FindAsync(id);
            if (area != null)
            {
                _context.Areas.Remove(area);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AreaExists(int id)
        {
          return (_context.Areas?.Any(e => e.AreaID == id)).GetValueOrDefault();
        }
    }
}

Controllers/ProblemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Mathemat.io.Data;
using Mathemat.io.Models;
using Microsoft.AspNetCore.Authorization;

namespace Mathematio.Controllers
{
    public class ProblemsController : Controller
    {
        private readonly MathematioContext _context;

        public enum DifficultyLevel
        {
            Easy,
            Medium,
            Hard
        }

        public ProblemsController(MathematioContext context)
        {
            _context = context;
        }

        // GET: Problems
        public async Task<IActionResult> Index(string? title,int? difficulty,string? areaName)
        {
            var filteredProblems = _context.Problems.AsQueryable();
            if(title != null)
            {
                filteredProblems = filteredProblems.Where(p => p.Title.Contains(title));
            }
            if(difficulty != null)
            {
                filteredProblems = filteredProblems.Where(p => (int)p.Difficulty == difficulty);
            }
            if(areaName != null)
            {
                int areaID = _context.Areas.First(a => a.Name.Equals(areaName)).AreaID;
                var problemAreas = _context.ProblemAreas.Where(pa => pa.AreaID == areaID);
                filteredProblems = problemAreas.Join<ProblemAreas,Problem,int,Problem>(filteredProblems, pa => pa.ProblemID, p => p.ProblemId,(pa,p)=>p);
            }

            ViewBag.AreaList = new SelectList(_context.Areas.Select(a => a.Name).OrderBy(s => s));

            return _context.Problems != null ? 
                          View(await filteredProblems.ToListAsync()) :
                          Problem("Entity set 'MathematioContext.Problems'  is null.");
        }

        // GET: Problems/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Problems == null)
            {
                return NotFound();
            }

            var problem = await _context.Problems
                .FirstOrDefaultAsync(m => m.ProblemId == id);
            if (problem == null)
            {
                return NotFound();
            }

            return View(problem);
        }

        // GET: Problems/Create
        [Authorize(Roles = "Admin,Mentor")]
        public IActionResult Create()
        {
            ViewBag.Areas = new SelectList(_context.Set<Area>(), "AreaID", "Name");
            ViewBag.Authors = new SelectList(_context.Set<Mentor>(), "MentorID", "FirstName");
            return View();
        }

        // POST: Problems/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Mentor")]
        public async Task<IActionResult> Create([Bind("ProblemId,Title,Difficulty,Description,DateAdded,AreaIDs,AuthorIDs")] Problem problem)
        {
            if (ModelState.IsValid)
            {
                _context.Add(problem);
                _context.SaveChanges();
                foreach(var AreaID in problem.AreaIDs)
                {
                    ProblemAreas problemAreas = new ProblemAreas();
                    problemAreas.ProblemID = problem.ProblemId;
                    problemAreas.AreaID = AreaID;
                    await _context.ProblemAreas.AddAsync(problemAreas);
                }
                await _context.SaveChangesAsync();
                foreach (var AuthorID in problem.AuthorIDs)
                {
                    ProblemAuthors problemAuthors = new ProblemAuthors();
                    problemAuthors.ProblemID = problem.ProblemId;
                    problemAuthors.MentorID = AuthorID;
                    await _context.ProblemAuthors.AddAsync(problemAuthors);
                }
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            return View(problem);
        }

        // GET: Problems/Edit/5
        [Authorize(Roles = "Admin,Mentor")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Problems == null)
            {
                return NotFound();
            }

            var problem = await _context.Problems.FindAsync(id);
            if (problem == null)
            {
                return NotFound();
            }
            return View(problem);
        }

        // POST: Problems/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Mentor")]
        public async Task<IActionResult> Edit(int id, [Bind("ProblemId,Title,Difficulty,Description,DateAdded")] Problem problem)
        {
            if (id != problem.ProblemId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(problem);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProblemExists(problem.ProblemId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(problem);
        }

        // GET: Problems/Delete/5
        [Authorize(Roles = "Admin,Mentor")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Problems == null)
            {
                return NotFound();
            }

            var problem = await _context.Problems
                .FirstOrDefaultAsync(m => m.ProblemId == id);
            if (problem == null)
            {
                return NotFound();
            }

            return View(problem);
        }

        // POST: Problems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Mentor")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Problems == null)
            {
                return Problem("Entity set 'MathematioContext.Problems'  is null.");
            }
            var problem = await _context.Problems.FindAsync(id);
            if (problem != null)
            {
                _context.Problems.Remove(problem);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProblemExists(int id)
        {
          return (_context.Problems?.Any(e => e.ProblemId == id)).GetValueOrDefault();
        }
    }
}

Views/Areas/Create.cshtml
@model Mathemat.io.Models.Area

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Area</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Areas/Delete.cshtml
@model Mathemat.io.Models.Area

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Area</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="AreaID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Areas/Details.cshtml
@model Mathemat.io.Models.Area

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Area</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.AreaID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Areas/Edit.cshtml
@model Mathemat.io.Models.Area

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Area</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="AreaID" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Areas/Index.cshtml
@model IEnumerable<Mathemat.io.Models.Area>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<form asp-controller="Areas" asp-action="Index" method="get">
    <label>Name:</label>
    <input name="name"/>
    <button class="btn btn-info" type="submit">Filter</button>
</form>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                <a class="btn btn-light" asp-action="Edit" asp-route-id="@item.AreaID">Edit</a> 
                <a class="btn btn-light" asp-action="Details" asp-route-id="@item.AreaID">Details</a> 
                <a class="btn btn-light" asp-action="Delete" asp-route-id="@item.AreaID">Delete</a> 
                <a class="btn btn-light" asp-controller="Problems" asp-action="Index" asp-route-areaName="@item.Name">Problems</a>
            </td>
        </tr>
}
    </tbody>
</table>