Models/Contestant.cs
using System.ComponentModel.DataAnnotations;

namespace Mathemat.io.Models
{
    public class Contestant
    {
        [Key]
        public int ContestantID { get; set; }

        [Required]
        [StringLength(30)]
        public string FirstName { get; set; } = string.Empty;

        [Required]
        [StringLength(30)]
        public string LastName { get; set; } = string.Empty;

        [StringLength(30)]
        public string? Country { get; set; }

        [DataType(DataType.Date)]
        public DateTime BirthDate {get; set; }

        [StringLength(100)]
        public string? School { get; set; }

        public int ContestantPoints { get; set; } = 0;

        public ICollection<Contest> Contests { get; set; }

        public ICollection<Mentor> Mentors { get; set; }


    }
}

Controllers/ContestantsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Mathemat.io.Data;
using Mathemat.io.Models;
using Mathematio.Areas.Identity.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace Mathematio.Controllers
{
    public class ContestantsController : Controller
    {
        private readonly MathematioContext _context;
        public IServiceProvider _serviceProvider;

        public ContestantsController(MathematioContext context, IServiceProvider serviceProvider)
        {
            _context = context;
            _serviceProvider = serviceProvider;
        }

        // GET: Contestants
        public async Task<IActionResult> Index(string? fn,string? ln,string? country)
        {
            var contestantFilter = _context.Contestants.AsQueryable();
            if (!string.IsNullOrEmpty(fn))
            {
                contestantFilter = contestantFilter.Where(c => c.FirstName.Contains(fn));
            }
            if (!string.IsNullOrEmpty(ln))
            {
                contestantFilter = contestantFilter.Where(c => c.LastName.Contains(ln));
            }
            if (!string.IsNullOrEmpty(country))
            {
                contestantFilter = contestantFilter.Where(c => c.Country.Equals(country));
            }
            var countryNames = _context.Contestants.GroupBy(c => c.Country).Select(g => g.Key).ToArray();
            ViewBag.CountryList = new SelectList(countryNames);
            return View(await contestantFilter.ToListAsync());
        }

        // GET: Contestants/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Contestants == null)
            {
                return NotFound();
            }

            var contestant = await _context.Contestants
                .FirstOrDefaultAsync(m => m.ContestantID == id);
            if (contestant == null)
            {
                return NotFound();
            }

            return View(contestant);
        }

        // GET: Contestants/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Contestants/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("ContestantID,FirstName,LastName,Country,BirthDate,School,ContestantPoints")] Contestant contestant)
        {
            if (ModelState.IsValid)
            {
                _context.Add(contestant);
                await _context.SaveChangesAsync();
                var UserManager = _serviceProvider.GetRequiredService<UserManager<MathematioUser>>();
                var User = new MathematioUser();
                User.Email = "contestant" + contestant.ContestantID + "@mathemat.io";
                User.UserName = "contestant" + contestant.ContestantID + "@mathemat.io";
                User.LinkId = contestant.ContestantID;
                User.EmailConfirmed = true;
                string userPWD = "Contestant" + contestant.ContestantID;
                IdentityResult chkUser = await UserManager.CreateAsync(User, userPWD);
                if (chkUser.Succeeded) { var result1 = await UserManager.AddToRoleAsync(User, "Contestant"); }
                return RedirectToAction(nameof(Index));
            }
            return View(contestant);
        }

        // GET: Contestants/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Contestants == null)
            {
                return NotFound();
            }

            var contestant = await _context.Contestants.FindAsync(id);
            if (contestant == null)
            {
                return NotFound();
            }
            return View(contestant);
        }

        // POST: Contestants/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("ContestantID,FirstName,LastName,Country,BirthDate,School,ContestantPoints")] Contestant contestant)
        {
            if (id != contestant.ContestantID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(contestant);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ContestantExists(contestant.ContestantID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(contestant);
        }

        // GET: Contestants/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Contestants == null)
            {
                return NotFound();
            }

            var contestant = await _context.Contestants
                .FirstOrDefaultAsync(m => m.ContestantID == id);
            if (contestant == null)
            {
                return NotFound();
            }

            return View(contestant);
        }

        // POST: Contestants/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Contestants == null)
            {
                return Problem("Entity set 'MathematioContext.Contestants'  is null.");
            }
            var contestant = await _context.Contestants.FindAsync(id);
            if (contestant != null)
            {
                _context.Contestants.Remove(contestant);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ContestantExists(int id)
        {
          return (_context.Contestants?.Any(e => e.ContestantID == id)).GetValueOrDefault();
        }
    }
}

Views/Contestants/Create.cshtml
@model Mathemat.io.Models.Contestant

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Contestant</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Country" class="control-label"></label>
                <input asp-for="Country" class="form-control" />
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BirthDate" class="control-label"></label>
                <input asp-for="BirthDate" class="form-control" />
                <span asp-validation-for="BirthDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="School" class="control-label"></label>
                <input asp-for="School" class="form-control" />
                <span asp-validation-for="School" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContestantPoints" class="control-label"></label>
                <input asp-for="ContestantPoints" class="form-control" />
                <span asp-validation-for="ContestantPoints" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Contestants/Delete.cshtml
@model Mathemat.io.Models.Contestant

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Contestant</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Country)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BirthDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.School)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.School)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ContestantPoints)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ContestantPoints)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ContestantID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Contestants/Details.cshtml
@model Mathemat.io.Models.Contestant

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Contestant</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Country)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BirthDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.School)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.School)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ContestantPoints)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ContestantPoints)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.ContestantID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Contestants/Edit.cshtml
@model Mathemat.io.Models.Contestant

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Contestant</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ContestantID" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Country" class="control-label"></label>
                <input asp-for="Country" class="form-control" />
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BirthDate" class="control-label"></label>
                <input asp-for="BirthDate" class="form-control" />
                <span asp-validation-for="BirthDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="School" class="control-label"></label>
                <input asp-for="School" class="form-control" />
                <span asp-validation-for="School" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContestantPoints" class="control-label"></label>
                <input asp-for="ContestantPoints" class="form-control" />
                <span asp-validation-for="ContestantPoints" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Contestants/Index.cshtml
@model IEnumerable<Mathemat.io.Models.Contestant>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<form asp-controller="Contestants" asp-action="Index" method="get">
    <label>First Name:</label>
    <input type="text" name="fn"/>

    <label>Last Name:</label>
    <input type="text" name="ln"/>

    <label>Country:</label>
    <select name="country" asp-items="@ViewBag.CountryList">
        <option value="">All</option>
    </select>

    <button class="btn btn-info" type="submit">Filter</button>
</form>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Country)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BirthDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.School)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ContestantPoints)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Country)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BirthDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.School)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ContestantPoints)
            </td>
            <td>
                <a class="btn btn-light" asp-action="Edit" asp-route-id="@item.ContestantID">Edit</a> 
                <a class="btn btn-light" asp-action="Details" asp-route-id="@item.ContestantID">Details</a> 
                <a class="btn btn-light" asp-action="Delete" asp-route-id="@item.ContestantID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>